import express from "express";
import cors from "cors";
import auth from "./middleware/auth.middleware.js";
import authRoutes from "./routes/auth.routes.js";
import productRoutes from "./routes/product.routes.js";
import orderRoutes from "./routes/order.routes.js";
import wishlistRoutes from "./routes/wishlist.routes.js";
import browsingRoutes from "./routes/browsing.routes.js";
import profileRoutes from "./routes/profile.routes.js";
import recommendationRoutes from "./routes/recommendation.routes.js";
import recommendationEventRoutes from "./routes/recommendation-event.routes.js";
import { config } from "./config.js";
const app=express();
app.use(cors({origin:config.corsOrigin}));
app.use(express.json());
app.get("/api/health",(_,res)=>res.json({ok:true}));
app.use("/api/auth",authRoutes);
app.use("/api",auth);
app.use("/api/products",productRoutes);
app.use("/api/orders",orderRoutes);
app.use("/api/wishlist",wishlistRoutes);
app.use("/api/browsing-history",browsingRoutes);
app.use("/api/profile",profileRoutes);
app.use("/api/recommendations",recommendationRoutes);
app.use("/api/recommendation-events",recommendationEventRoutes);
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({message:err.message||"Server error"});});
export default app;
